; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    fastled/FastLED @ ^3.9.20
    ; ESP8266WebServer - часть фреймворка Arduino для ESP8266, не нужно добавлять явно
    ; ESP8266WiFi - аналогично
    ; ArduinoJson - понадобится позже для сохранения настроек или сложного обмена данными
    ; earlephilhower/ESP8266LittleFS@^3.0.0 ; Для работы с файловой системой
build_flags = -D FASTLED_ESP8266_RAW_PIN_ORDER ; Важно для FastLED на ESP8266