#ifndef WEBPAGE_H
#define WEBPAGE_H

#include <Arduino.h>
#include <ESP8266WebServer.h>
#include <string>

const byte MAX_SLIDER_VALUE = 255;
const byte FACTOR_VALUE = 16;

// [\n";
// "{ id: 0, name: \"Q\", type: \"normal\", speed: 64, scale: 64 },\n";
// "{ id: 1, name: \"W\", type: \"normal\", speed: 64, scale: 64 },\n";
// "{ id: 2, name: \"E\", type: \"normal\", speed: 64, scale: 64 },\n";
// "{ id: 3, name: \"R\", type: \"normal\", speed: 64, scale: 64 },\n";
// "{ id: 4, name: \"T\", type: \"normal\", speed: 64, scale: 64 },\n";
// "{ id: 5, name: \"Y\", type: \"normal\", speed: 64, scale: 64 },\n";
// "];\n";
String addMode(EffectData *effects, byte size)
{
    String modesArray = "[\n";
    for (byte i = 0; i < size; i++)
    {
        EffectData effect = effects[i];
        modesArray += "{ id: " + String(effect.id);
        modesArray += ", name: \"" + effect.name;
        modesArray += "\", type: \"" + effect.type;
        modesArray += "\", speed: " + String(effect.speed);
        modesArray += ", scale: " + String(effect.scale);
        modesArray += "},\n";
    }
    modesArray += "];\n";
    Serial.println(modesArray);
    return modesArray;
}

String createWebPage(LedData data)
{

    // htmlPage += "var modeIndex = " + String(data.currentEffect) + ";\n";
    // htmlPage += "var brightness = " + String(data.brightness) + ";\n";
    // htmlPage += "const maxSlider = " + String(MAX_SLIDER_VALUE) + ";\n";
    // htmlPage += "const factor = " + String(FACTOR_SLIDER_VALUE) + ";\n";
    // htmlPage += "const modes = " + addMode(data.effectData, LedData::COUNT_MODE);
    String htmlPage = "";
    htmlPage += "<!DOCTYPE html>\n";
    htmlPage += "<html>\n";
    htmlPage += "<head>\n";
    htmlPage += "<title>SandwichLamp</title>\n";
    htmlPage += "<style>\n";
    htmlPage += "body {\n";
    htmlPage += "text-align: center;\n";
    htmlPage += "font-family: Arial, sans-serif;\n";
    htmlPage += "flex-direction: column;\n";
    htmlPage += "display: flex;\n";
    htmlPage += "flex-direction: column;\n";
    htmlPage += "align-items: center;\n";
    htmlPage += "justify-content: center;\n";
    htmlPage += "}\n";
    htmlPage += ".card {\n";
    htmlPage += "display: inline-block;\n";
    htmlPage += "padding: 20px;\n";
    htmlPage += "border-radius: 10px;\n";
    htmlPage += "background-color: #f0f0f0;\n";
    htmlPage += "box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.2);\n";
    htmlPage += "margin-bottom: 16px;\n";
    htmlPage += "}\n";
    htmlPage += ".btn {\n";
    htmlPage += "margin: 10px;\n";
    htmlPage += "cursor: pointer;\n";
    htmlPage += "border-radius: 50%;\n";
    htmlPage += "width: 50px;\n";
    htmlPage += "height: 50px;\n";
    htmlPage += "font-size: 24px;\n";
    htmlPage += "display: inline-flex;\n";
    htmlPage += "justify-content: center;\n";
    htmlPage += "align-items: center;\n";
    htmlPage += "background-color: #999;\n";
    htmlPage += "color: #fff;\n";
    htmlPage += "border: none;\n";
    htmlPage += "outline: none;\n";
    htmlPage += "box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.2);\n";
    htmlPage += "}\n";
    htmlPage += ".btn:hover {\n";
    htmlPage += "background-color: #777;\n";
    htmlPage += "}\n";
    htmlPage += "#slider {\n";
    htmlPage += "vertical-align: middle;\n";
    htmlPage += "display: inline-block;\n";
    htmlPage += "}\n";
    htmlPage += "#output {\n";
    htmlPage += "font-size: 24px;\n";
    htmlPage += "display: inline-block;\n";
    htmlPage += "margin: 0 10px;\n";
    htmlPage += "}\n";
    htmlPage += ".label {\n";
    htmlPage += "font-size: 18px;\n";
    htmlPage += "margin-bottom: 10px;\n";
    htmlPage += "}\n";
    htmlPage += "</style>\n";
    htmlPage += "<script>\n";
    htmlPage += "var modeIndex = " + String(data.currentEffect) + ";\n";
    htmlPage += "var brightness = " + String(data.brightness) + ";\n";
    htmlPage += "const maxSlider = " + String(MAX_SLIDER_VALUE) + ";\n";
    htmlPage += "const factor = " + String(FACTOR_VALUE) + ";\n";
    htmlPage += "const modes = " + addMode(data.effectData, LedData::COUNT_MODE);
    htmlPage += "window.onload = function () {\n";
    htmlPage += "setupSlider(document.getElementById(\"brightness\"), brightness, function (newValue) {\n";
    htmlPage += "brightness = newValue;\n";
    htmlPage += "});\n";
    htmlPage += "updateMode(modeIndex);\n";
    htmlPage += "};\n";
    htmlPage += "function updateMode(index) {\n";
    htmlPage += "const mode = modes[index];\n";
    htmlPage += "switch (mode.type) {\n";
    htmlPage += "case \"1\":\n";
    htmlPage += "setupNormal(mode);\n";
    htmlPage += "break;\n";
    htmlPage += "default:\n";
    htmlPage += "setupNormal(mode);\n";
    htmlPage += "}\n";
    htmlPage += "};\n";
    htmlPage += "function setupNormal(mode) {\n";
    htmlPage += "setupModeSlider(document.getElementById(\"mode\"), mode);\n";
    htmlPage += "setupSlider(document.getElementById(\"speed\"), mode.speed, function (newValue) {\n";
    htmlPage += "mode.speed = newValue;\n";
    htmlPage += "});\n";
    htmlPage += "setupSlider(document.getElementById(\"scale\"), mode.scale, function (newValue) {\n";
    htmlPage += "mode.scale = newValue;\n";
    htmlPage += "});\n";
    htmlPage += "};\n";
    htmlPage += "function setupModeSlider(element, mode) {\n";
    htmlPage += "var slider = element.querySelector(\"#slider\");\n";
    htmlPage += "var output = element.querySelector(\"#output\");\n";
    htmlPage += "slider.max = modes.length - 1;\n";
    htmlPage += "output.innerHTML = mode.name;\n";
    htmlPage += "slider.value = modeIndex;\n";
    htmlPage += "var prevSliderValue = slider.value;\n";
    htmlPage += "slider.oninput = function () {\n";
    htmlPage += "if (prevSliderValue != this.value) {\n";
    htmlPage += "updateModeData(element, this.value);\n";
    htmlPage += "prevSliderValue = this.value;\n";
    htmlPage += "}\n";
    htmlPage += "}\n";
    htmlPage += "var btnIncrement = element.querySelector(\"#btnIncrement\");\n";
    htmlPage += "var btnDecrement = element.querySelector(\"#btnDecrement\");\n";
    htmlPage += "btnIncrement.onclick = function () {\n";
    htmlPage += "if (parseInt(slider.value) < parseInt(slider.max)) {\n";
    htmlPage += "updateModeData(element, parseInt(slider.value) + 1);\n";
    htmlPage += "}\n";
    htmlPage += "}\n";
    htmlPage += "btnDecrement.onclick = function () {\n";
    htmlPage += "if (parseInt(slider.value) > parseInt(slider.min)) {\n";
    htmlPage += "updateModeData(element, parseInt(slider.value) - 1);\n";
    htmlPage += "}\n";
    htmlPage += "}\n";
    htmlPage += "};\n";
    htmlPage += "function updateModeData(element, value) {\n";
    htmlPage += "var xhttp = new XMLHttpRequest();\n";
    htmlPage += "var slider = element.querySelector(\"#slider\");\n";
    htmlPage += "var output = element.querySelector(\"#output\");\n";
    htmlPage += "xhttp.onreadystatechange = function () {\n";
    htmlPage += "if (this.readyState == 4 && this.status == 200) {\n";
    htmlPage += "console.log(this.responseText);\n";
    htmlPage += "modeIndex = value;\n";
    htmlPage += "updateMode(value);\n";
    htmlPage += "}\n";
    htmlPage += "}\n";
    htmlPage += "xhttp.open(\"GET\", \"/\" + element.id + \"?value=\" + value, true);\n";
    htmlPage += "xhttp.send();\n";
    htmlPage += "modeIndex = value;\n";
    htmlPage += "updateMode(value);\n";
    htmlPage += "};\n";
    htmlPage += "function setupSlider(element, initialValue, callback) {\n";
    htmlPage += "const slider = element.querySelector(\"#slider\");\n";
    htmlPage += "const output = element.querySelector(\"#output\");\n";
    htmlPage += "const value = Math.round(initialValue / factor);\n";
    htmlPage += "var prevSliderValue = value;\n";
    htmlPage += "output.innerHTML = value;\n";
    htmlPage += "slider.value = value;\n";
    htmlPage += "slider.max = Math.round(maxSlider / factor);\n";
    htmlPage += "slider.oninput = function () {\n";
    htmlPage += "if (prevSliderValue != this.value) {\n";
    htmlPage += "updateSliderData(element, this.value, callback);\n";
    htmlPage += "prevSliderValue = this.value;\n";
    htmlPage += "}\n";
    htmlPage += "}\n";
    htmlPage += "const btnIncrement = element.querySelector(\"#btnIncrement\");\n";
    htmlPage += "const btnDecrement = element.querySelector(\"#btnDecrement\");\n";
    htmlPage += "btnIncrement.onclick = function () {\n";
    htmlPage += "if (parseInt(slider.value) < parseInt(slider.max)) {\n";
    htmlPage += "updateSliderData(element, parseInt(slider.value) + 1, callback);\n";
    htmlPage += "}\n";
    htmlPage += "}\n";
    htmlPage += "btnDecrement.onclick = function () {\n";
    htmlPage += "if (parseInt(slider.value) > parseInt(slider.min)) {\n";
    htmlPage += "updateSliderData(element, parseInt(slider.value) - 1, callback);\n";
    htmlPage += "}\n";
    htmlPage += "}\n";
    htmlPage += "};\n";
    htmlPage += "function updateSliderData(element, value, callback) {\n";
    htmlPage += "const xhttp = new XMLHttpRequest();\n";
    htmlPage += "const slider = element.querySelector(\"#slider\");\n";
    htmlPage += "const output = element.querySelector(\"#output\");\n";
    htmlPage += "const responseValue = (value * factor >= maxSlider) ? maxSlider : value * factor;\n";
    htmlPage += "xhttp.onreadystatechange = function () {\n";
    htmlPage += "if (this.readyState == 4 && this.status == 200) {\n";
    htmlPage += "output.innerHTML = value\n";
    htmlPage += "slider.value = value\n";
    htmlPage += "callback(responseValue);\n";
    htmlPage += "}\n";
    htmlPage += "}\n";
    htmlPage += "xhttp.open(\"GET\", \"/\" + element.id + \"?value=\" + responseValue, true);\n";
    htmlPage += "xhttp.send();\n";
    htmlPage += "// output.innerHTML = value\n";
    htmlPage += "// slider.value = value\n";
    htmlPage += "// callback(responseValue);\n";
    htmlPage += "};\n";
    htmlPage += "</script>\n";
    htmlPage += "</head>\n";
    htmlPage += "<body>\n";
    htmlPage += "<h1>SandwichLamp</h1>\n";
    htmlPage += "<!-- <p>Welcome to my website.</p> -->\n";
    htmlPage += "<div class=\"card\" id=\"brightness\">\n";
    htmlPage += "<div class=\"label\">Brightness:<span id=\"output\">50</span></div>\n";
    htmlPage += "<button id=\"btnDecrement\" class=\"btn\">-</button>\n";
    htmlPage += "<input type=\"range\" id=\"slider\" min=\"0\">\n";
    htmlPage += "<button id=\"btnIncrement\" class=\"btn\">+</button>\n";
    htmlPage += "</div>\n";
    htmlPage += "<div class=\"card\" id=\"mode\">\n";
    htmlPage += "<div class=\"label\">Mode:<span class=\"label\" id=\"output\">0</span></div>\n";
    htmlPage += "<button id=\"btnDecrement\" class=\"btn\">-</button>\n";
    htmlPage += "<input type=\"range\" id=\"slider\" min=\"0\">\n";
    htmlPage += "<button id=\"btnIncrement\" class=\"btn\">+</button>\n";
    htmlPage += "</div>\n";
    htmlPage += "<div class=\"card\" id=\"speed\">\n";
    htmlPage += "<div class=\"label\">Speed:<span id=\"output\">50</span></div>\n";
    htmlPage += "<button id=\"btnDecrement\" class=\"btn\">-</button>\n";
    htmlPage += "<input type=\"range\" id=\"slider\" min=\"0\">\n";
    htmlPage += "<button id=\"btnIncrement\" class=\"btn\">+</button>\n";
    htmlPage += "</div>\n";
    htmlPage += "<div class=\"card\" id=\"scale\">\n";
    htmlPage += "<div class=\"label\">Scale:<span id=\"output\">50</span></div>\n";
    htmlPage += "<button id=\"btnDecrement\" class=\"btn\">-</button>\n";
    htmlPage += "<input type=\"range\" id=\"slider\" min=\"0\">\n";
    htmlPage += "<button id=\"btnIncrement\" class=\"btn\">+</button>\n";
    htmlPage += "</div>\n";
    htmlPage += "</body>\n";
    htmlPage += "</html>\n";

    return htmlPage;
};

#endif